//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int BookId { get; set; }
        public string TitleEn { get; set; }
        public string TitleAl { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionAl { get; set; }
    
        public virtual ICollection<Section> Sections { get; set; }
    }
}
