//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graph
    {
        public int GraphId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string GraphTableUrlAl { get; set; }
        public string GraphTableUrlEn { get; set; }
        public string GraphTableQuery { get; set; }
        public Nullable<int> GraphOrder { get; set; }
        public Nullable<int> GraphTypeId { get; set; }
        public Nullable<int> Graph1 { get; set; }
    
        public virtual GraphType GraphType { get; set; }
        public virtual Section Section { get; set; }
    }
}
