//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GraphType
    {
        public GraphType()
        {
            this.Graphs = new HashSet<Graph>();
        }
    
        public int GraphTypeId { get; set; }
        public string GraphTypeEn { get; set; }
        public string GraphTypeAl { get; set; }
    
        public virtual ICollection<Graph> Graphs { get; set; }
    }
}
