//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TableId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string TableMetadataUrlEn { get; set; }
        public string TableQuery { get; set; }
        public string TableMetadataUrlAl { get; set; }
        public Nullable<int> TableOrder { get; set; }
        public Nullable<int> NumberOfContents { get; set; }
        public Nullable<int> TableNo { get; set; }
        public string Cols { get; set; }
        public string Rows { get; set; }
        public string ColsEn { get; set; }
        public string RowEn { get; set; }
        public string TitleAl { get; set; }
        public string TitleEn { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
